export const GET_POKEMONES = 'GET_POKEMONES';
export const GET_PROFILE_POKEMON = 'GET_PROFILE_POKEMON';
export const GET_NEXT_POKEMON = 'GET_NEXT_POKEMON';
export const GET_PREVIOUS_POKEMON = 'GET_PREVIOUS_POKEMON';
